name: Entrega Contínua

on:
  workflow_call:

jobs:
  
  EC2:
    runs-on: ubuntu-latest
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
        # Artifact name
          name: programa
      - uses: actions/checkout@v3
      
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}
          EXCLUDE: "postgres-data"
